source "https://rubygems.org"

ruby "2.2.2"

gem "coderay"
gem "coffee-rails"
gem "devise"
gem "faker"
gem "foundation-rails"
gem "haml-rails"
gem "jquery-rails"
gem "nokogiri"
gem "pg"
gem "rails"
gem "redcarpet"
gem "sass-rails"
gem "simple_form"
gem "turbolinks"
gem "uglifier"
gem "capybara"
gem "selenium-webdriver"

group :development do
  gem "byebug"
  gem "mailcatcher"
  gem "spring"
  gem "quiet_assets"
  gem "web-console"
end

group :production do
  gem "rails_12factor"
end

group :test do
  gem "shoulda-matchers"
end

group :test, :development do
  gem "guard-livereload", "~> 2.4", require: false
  gem "guard-rspec"
  gem "launchy"
  gem "pry"
  gem "rspec-rails"
  gem "database_cleaner"
end
